name: Replace README

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: false
  issue_comment:
    types: [created]

env:
  GITHUB_NAME: kenwoodjw
  GITHUB_EMAIL: blackxin55@gmail.com
  BOOKMARK_ISSUE_ID: 2


jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Replace README
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_numbe '${{ github.event.issue.number }}' --issue_label_name '${{ github.event.issue.labels[0].name }}' 
        if: github.event.issue.number != ${{ env.BOOKMARK_ISSUE_ID }}
      - name: Make bookmark
        run: |
          source venv/bin/activate
          python make_bookmark.py ${{ secrets.G_T }} ${{ github.repository }}
        if:  github.event.issue.number == ${{ env.BOOKMARK_ISSUE_ID }}
      - name: Push README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "generated readme" || echo "no need to commit "
          git push || echo "no file change"
